name: Sync New Assets

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.10
      - name: go build
        working-directory: .
        run: go build -o bin/azure-assets ./cmd/azure-assets

      - name: run application
        run: ./bin/azure-assets

      - name: Commit and push changes
        shell: bash
        continue-on-error: true
        run: |
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "chore:Updated new assets"
          git push
